//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAccounting.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expenditure_Invoice()
        {
            this.Accounting_Card_Expenditure = new HashSet<Accounting_Card_Expenditure>();
            this.Accounting_Card_Expenditure1 = new HashSet<Accounting_Card_Expenditure>();
            this.Receipt_Invoice = new HashSet<Receipt_Invoice>();
        }
    
        public int ID_Expenditure_Invoice { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<int> ID_Storage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting_Card_Expenditure> Accounting_Card_Expenditure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting_Card_Expenditure> Accounting_Card_Expenditure1 { get; set; }
        public virtual Expenditure_Inventory Expenditure_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt_Invoice> Receipt_Invoice { get; set; }
    }
}
